### ISSUE TITLE
Task 5 submission

### ISSUE THREAD

**Issue by VojtaT04** [stany9g/upgraded-waffle#8]
When I try to submit my work for Task 5, the web is slower with the upload than usual and then says:

<img src="https://raw.githubusercontent.com/VojtaT04/Errors/c6b949953a1b46434d1c9c94c71f4622597ffe4a/Task5%20Error.svg">
which makes me believe that the server doesn't have access to the testing program.

**Comment by stany9g** [comment]
Well, it is not really slower. Your while(true) does not end and then you are in an infinite loop waiting for the timeout. 

But actually, there was a bug on my side. That on cleaned up, the process was still holding the FlippingPoint.dll so denied was because it could not delete temp folder where I run your solution. Now you should get an appropriate Timeout.

TIP:
Try condition in while about your indexes
